biostar/forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django.urls import include, path  # For django versions from 2.0 and up
import debug_toolbar
from django.views.generic import TemplateView

from biostar.forum import views
from biostar.accounts.views import image_upload_view
from biostar.forum import ajax, api, feed
from biostar.accounts.urls import account_patterns
from biostar.forum.sitemaps import StaticSitemap, DynamicSitemap

from biostar.planet.urls import planet_patterns

sitemaps = {
    'static': StaticSitemap,
    'dynamic': DynamicSitemap
}

forum_patterns = [

    # Main entry. Post listing.
    path('', views.home, name='home'),
    path('latest/', views.latest, name='post_list'),

    path(r'pages/<str:fname>/', views.pages, name='pages'),

    path('votes/', views.myvotes, name='myvotes'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('following/', views.following, name='following'),
    path('myposts/', views.myposts, name='myposts'),
    path('mytags/', views.mytags, name='mytags'),
    path('p/<str:uid>/', views.post_view, name='post_view'),

    path('post/<slug:slug>/', views.post_slug_details, name='post_view_slug'),

    path('post/search/', views.post_search, name='post_search'),

    path('new/post/', views.new_post, name='post_create'),

    path('b/list/', views.badge_list, name='badge_list'),
    path('t/list/', views.tags_list, name='tags_list'),

    path('b/view/<str:uid>/', views.badge_view, name='badge_view'),

    # Ajax calls
    path('ajax/digest/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/vote/', ajax.ajax_vote, name='vote'),
    path('ajax/test/', ajax.ajax_test, name='ajax_test'),
    path('ajax/subscribe/', ajax.ajax_subs, name='ajax_sub'),
    path('ajax/delete/', ajax.ajax_delete, name='ajax_delete'),
    path('drag/and/drop/', ajax.drag_and_drop, name='drag_and_drop'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/digest/<str:uid>/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/edit/<str:uid>/', ajax.ajax_edit, name='ajax_edit'),
    path('ajax/comment/create/', ajax.ajax_comment_create, name='ajax_comment_create'),
    path('inplace/form/', ajax.inplace_form, name='inplace_form'),
    path('ajax/user/image/<str:username>/', ajax.user_image, name='user_image'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/report/spam/<str:post_uid>/', ajax.report_spam, name='report_spam'),
    path('release/<str:uid>/', ajax.release_suspect, name='release_suspect'),
    #path('most/recent/users/', ajax.most_recent_users, name='most_recent_users'),

    path('moderate/<str:uid>/', views.post_moderate, name="post_moderate"),

    # Community urls
    path('community/', views.community_list, name='community_list'),
    path('ajax/handle/search/', ajax.handle_search, name='handle_search'),

    # Api calls
    path(r'api/traffic/', api.traffic, name='api_traffic'),
    path(r'api/user/<str:uid>/', api.user_details, name='api_user'),
    path(r'api/tags/list/', api.tags_list, name='api_tags_list'),
    path(r'api/post/<str:uid>/', api.post_details, name='api_post'),
    path(r'api/vote/<str:uid>/', api.vote_details, name='api_vote'),
    path(r'api/watched/tags/<str:email>/', api.watched_tags, name='api_tags'),
    path(r'api/email/<str:email>/', api.user_email, name='user_email'),
    path(r'api/stats/day/<int:day>/', api.daily_stats_on_day, name='api_stats_on_day'),
    path(r'api/stats/date/<int:year>/<int:month>/<int:day>/', api.daily_stats_on_date,
         name='api_stats_on_date'),


    # RSS info page.
    path(r'info/rss/', feed.info, name='rss'),

    # RSS feeds
    path(r'feeds/latest/', feed.LatestFeed(), name='latest_feed'),
    path(r'feeds/tag/<str:text>/', feed.TagFeed(), name='tag_feed'),
    path(r'feeds/user/<str:text>/', feed.UserFeed(), name='user_feed'),
    path(r'feeds/post/<str:text>/', feed.PostFeed(), name='post_feed' ),
    path(r'feeds/type/<str:text>/', feed.PostTypeFeed(), name='post_type'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    #add the robots.txt file
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),



    #path(r'^feeds/planet/$', feed.PlanetFeed(), name='planet-feed'),

]


urlpatterns = [

    # Main entry. Post listing.
    path('', include(forum_patterns)),

    # Include the accounts urls
    path('accounts/', include(account_patterns)),

    # Include the planet urls
    path('planet/', include(planet_patterns)),

]

if settings.PAGEDOWN_IMAGE_UPLOAD_ENABLED:

    urlpatterns += [
        # Pagedown image upload url.
        path('pagedown/image-upload/', image_upload_view, name="pagedown-image-upload")
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    urlpatterns += [
          path('__debug__/', include(debug_toolbar.urls)),
    ]

biostar/planet/urls.py
from django.urls import path, include
from biostar.planet import views


planet_patterns = [
    path('', views.blog_list, name="blog_list"),
]
urlpatterns = [

    # Get the reset/ urls
    path(r'', include(planet_patterns)),

]

biostar/server/urls.py
from django.conf import settings
from django.urls import path, include
import debug_toolbar
from django.conf.urls.static import static
from biostar.forum.urls import forum_patterns
from biostar.accounts.views import image_upload_view
from biostar.recipes.urls import recipes_patterns
import biostar.accounts.urls as accounts_urls
from biostar.planet.urls import planet_patterns


urlpatterns = [

    # Mount recipes urls on root.
    path(r'', include(recipes_patterns)),

    # Include forum urls
    path(r'forum/', include(forum_patterns)),

    # Include planets urls
    path(r'planet/', include(planet_patterns)),

    # Include the accounts urls
    path(r'accounts/', include(accounts_urls)),

]

if settings.PAGEDOWN_IMAGE_UPLOAD_ENABLED:

    urlpatterns += [
        # Pagedown image upload url.
        path('pagedown/image-upload/', image_upload_view, name="pagedown-image-upload")
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

biostar/urls.py
# Default url patters for the engine.
urlpatterns = []



biostar/recipes/models.py
import logging

import toml as hjson
import mistune
import urllib.parse
import base64
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from biostar.accounts.models import User
from . import util
from .const import *

logger = logging.getLogger("engine")


def join(*args):
    return os.path.abspath(os.path.join(*args))


class Bunch(object):
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)


def make_html(text, user=None):
    if user and user.profile.trusted:
        html = mistune.markdown(text, escape=False)
    else:
        html = mistune.markdown(text, escape=True)
    return html


def image_path(instance, filename):
    # Name the data by the filename.
    name, ext = os.path.splitext(filename)

    uid = util.get_uuid(6)
    dirpath = instance.get_project_dir()
    imgname = f"images/image-{uid}{ext}"

    # Uploads need to go relative to media directory.
    path = os.path.relpath(dirpath, settings.MEDIA_ROOT)

    imgpath = os.path.join(path, imgname)

    return imgpath


def snippet_images(instance, filename):
    # Name the data by the filename.
    name, ext = os.path.splitext(filename)
    uid = instance.uid or util.get_uuid(6)
    imgname = f"image-{uid}{ext}"

    dirpath = os.path.abspath(os.path.join(settings.MEDIA_ROOT, 'snippets', 'images'))

    # Uploads need to go relative to media directory.
    path = os.path.relpath(dirpath, settings.MEDIA_ROOT)
    imgpath = os.path.join(path, imgname)

    return imgpath


class Manager(models.Manager):

    def get_queryset(self):
        "Regular queries exclude deleted stuff"
        return super().get_queryset().select_related("owner", "owner__profile", "lastedit_user",
                                                     "lastedit_user__profile")


class SnippetType(models.Model):
    image = models.ImageField(default=None, blank=True, upload_to=snippet_images, max_length=MAX_FIELD_LEN)
    uid = models.CharField(max_length=MAX_TEXT_LEN, unique=True)
    # The name referring to this
    name = models.CharField(max_length=MAX_NAME_LEN)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    # Appears to all uses
    default = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(6)
        super(SnippetType, self).save(*args, **kwargs)


class Snippet(models.Model):
    help_text = models.CharField(max_length=MAX_TEXT_LEN)
    uid = models.CharField(max_length=MAX_TEXT_LEN, unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    command = models.CharField(max_length=MAX_TEXT_LEN, null=True)
    # Link a command to one type
    type = models.ForeignKey(SnippetType, on_delete=models.CASCADE)

    # Appears to all uses
    default = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(6)
        self.owner = self.owner or self.type.owner
        super(Snippet, self).save(*args, **kwargs)


def img_to_str(img, decode=True):
    exists = img and os.path.exists(img.path)

    img = img.path if exists else os.path.join(settings.STATIC_ROOT, "images", "placeholder.png")
    stream = open(img, 'rb').read()
    # Convert image to base64 string
    strimg = base64.b64encode(stream)
    if decode:
        # Decode from bytes to string, enables JSON serialization.
        strimg = strimg.decode()
    return strimg


class Project(models.Model):
    PUBLIC, SHAREABLE, PRIVATE = 1, 2, 3
    PRIVACY_CHOICES = [(PRIVATE, "Private"), (SHAREABLE, "Shared"), (PUBLIC, "Public")]

    # Rank in a project list.
    rank = models.FloatField(default=100)

    # The user that edited the object most recently.
    lastedit_user = models.ForeignKey(User, related_name='proj_editor', null=True, on_delete=models.CASCADE)
    lastedit_date = models.DateTimeField(default=timezone.now)

    # Limits who can access the project.
    privacy = models.IntegerField(default=PRIVATE, choices=PRIVACY_CHOICES)
    image = models.ImageField(default=None, blank=True, upload_to=image_path, max_length=MAX_FIELD_LEN)
    name = models.CharField(default="New Project", max_length=MAX_NAME_LEN)
    deleted = models.BooleanField(default=False)

    # We need to keep the owner.
    owner = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    text = models.TextField(default='Project description.', max_length=MAX_TEXT_LEN)

    html = models.TextField(default='html', max_length=MAX_LOG_LEN)
    date = models.DateTimeField(auto_now_add=True)
    # Internal uid that is not editable.
    uid = models.CharField(max_length=32, unique=True)

    # FilePathField points to an existing project directory.
    dir = models.FilePathField(max_length=MAX_FIELD_LEN, default='')

    sharable_token = models.CharField(max_length=32, null=True, unique=True)

    data_count = models.IntegerField(default=0, null=True, db_index=True)
    recipes_count = models.IntegerField(default=0, null=True, db_index=True)
    jobs_count = models.IntegerField(default=0, null=True, db_index=True)

    objects = Manager()

    def save(self, *args, **kwargs):
        now = timezone.now()
        self.date = self.date or now
        self.sharable_token = self.sharable_token or util.get_uuid(30)
        self.html = make_html(self.text, user=self.lastedit_user)
        self.name = self.name[:MAX_NAME_LEN]
        self.uid = self.uid or util.get_uuid(8)
        self.lastedit_user = self.lastedit_user or self.owner
        self.lastedit_date = now

        super(Project, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def uid_is_set(self):
        assert bool(self.uid.strip()), "Sanity check. UID should always be set."

    def url(self):
        self.uid_is_set()
        return reverse("project_view", kwargs=dict(uid=self.uid))

    def get_project_dir(self):
        return self.dir

    def get_data_dir(self):
        "Match consistency of data dir calls"
        return self.get_project_dir()

    def set_counts(self, save=True):
        """
        Set the data, recipe, and job count for this project
        """

        # Set the counts on current instance and also update in database.
        self.recipes_count = self.analysis_set.filter(project=self, deleted=False).count()
        self.data_count = self.data_set.filter(deleted=False).count()
        self.job_count = self.job_set.filter(deleted=False).count()

        Project.objects.filter(id=self.id).update(data_count=self.data_count,
                                                  recipes_count=self.recipes_count,
                                                  jobs_count=self.job_count)

    @property
    def is_public(self):
        return self.privacy == self.PUBLIC

    @property
    def is_private(self):
        return self.privacy == self.PRIVATE

    @property
    def project(self):
        return self

    @property
    def json_text(self):
        return hjson.dumps(self.api_data)

    @property
    def api_data(self):
        img = self.image
        strimg = img_to_str(img=img)

        json_data = dict(
            uid=self.uid,
            name=self.name,
            privacy=dict(self.PRIVACY_CHOICES)[self.privacy],
            text=self.text,
            url=settings.BASE_URL,
            project_uid=self.uid,
            id=self.pk,
            image=strimg,
            # Insert recipes API data in there as well.
            recipes=[
                r.api_data for r in self.analysis_set.all()
            ]
        )

        return json_data

    @property
    def summary(self):
        """
        Returns first line of text
        """
        lines = self.text.splitlines() or ['']
        first = lines[0]
        return first

    @property
    def delete_url(self):
        return reverse('project_delete', kwargs=dict(uid=self.uid))

    @property
    def is_shareable(self):
        return self.privacy == self.SHAREABLE

    def get_sharable_link(self):

        # Return a sharable link if the project is shareable
        if self.is_shareable:
            return reverse('project_share', kwargs=dict(token=self.sharable_token))

        return '/'

    def get_name(self):
        if self.deleted:
            return f'Deleted Project: {self.name}'
        return self.name


class Access(models.Model):
    """
    Allows access of users to Projects.
    """
    NO_ACCESS, READ_ACCESS, WRITE_ACCESS, SHARE_ACCESS = 1, 2, 3, 4
    ACCESS_CHOICES = [
        (NO_ACCESS, "No Access"),
        (READ_ACCESS, "Read Access"),
        (WRITE_ACCESS, "Write Access"),
        (SHARE_ACCESS, "Share Access"),
    ]

    ACCESS_MAP = dict(ACCESS_CHOICES)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    access = models.IntegerField(default=NO_ACCESS, choices=ACCESS_CHOICES, db_index=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} on {self.project.name}"

    def save(self, *args, **kwargs):
        super(Access, self).save(*args, **kwargs)


@receiver(post_save, sender=Project)
def update_access(sender, instance, created, raw, update_fields, **kwargs):
    # Give the owner WRITE ACCESS if they do not have it.
    entry = Access.objects.filter(user=instance.owner, project=instance, access=Access.WRITE_ACCESS)
    if entry.first() is None:
        entry = Access.objects.create(user=instance.owner, project=instance, access=Access.WRITE_ACCESS)


class Data(models.Model):
    PENDING, READY, ERROR, = 1, 2, 3
    STATE_CHOICES = [(PENDING, "Pending"), (READY, "Ready"), (ERROR, "Error")]
    state = models.IntegerField(default=PENDING, choices=STATE_CHOICES)

    LINK, UPLOAD, TEXTAREA = 1, 2, 3

biostar/recipes/templates/widgets/access_denied_message.html
{% if user.is_anonymous %}

   <i class="warning circle icon"></i> You must be logged in to perform that action.

{% else %}
  You need <span class="ui green label"><i class="unlock icon"></i> {{needed_access}}</span> to perform that action.

{%  endif %}

biostar/recipes/templates/widgets/clipboard.html
{% if count %}
    <div class="ui center aligned segment">
    <span class="ui blue message">

    <b>{{ count }} </b>{{ board }} on the clipboard.

    <span class="ui mini buttons">
        {% if is_recipe %}
            <a class="ui green clone button"><i class="clone outline icon"></i>Clone</a>
            <div class="or"></div>
        {% endif %}

        <a class="ui blue paste button"><i class="sticky note icon"></i>Paste</a>
        {# Files can not be moved, so the button is not shown. #}
        {% if movable %}
            <div class="or"></div>
            <a class="ui move button"><i class="crosshairs icon"></i>Move</a>
        {% endif %}

        <div class="or"></div>
        <a class="ui clear button">
            <i class="window close icon"></i> Clear
        </a>

    </span>
        {% if is_recipe %}
            <span class="muted">Cloned recipes remain synced with the original.</span>
        {% endif %}

    </span>
    </div>
{% endif %}

biostar/recipes/templates/widgets/created_by.html
{% load accounts_tags %}
{% load engine_tags %}
{% load humanize %}

{{ prefix }} {{ date|time_ago }}

{% if user %}
    by <a href="{% url 'user_profile'  user.profile.uid %}" >
        {{ user.profile.name }}
    </a>

{% endif %}

biostar/recipes/templates/widgets/delete_msg.html
{% if obj.deleted %}
    Deleted <b>{{ obj.name }}</b>.
    <a class="ui blue large label" href="{{ undo_url }}">
        <i class="undo icon"></i>Click here to restore.
    </a>
{% else %}
    Restored {{ obj.name }}
{% endif %}

biostar/recipes/templates/widgets/files_list.html
{% load engine_tags %}
{% load humanize %}


{% if paths %}
    {% if not show_all %}

        <a class="ui label" onclick="window.history.back()"> <i class="left chevron icon"></i>Back</a>

    {% endif %}

    <div class="ui relaxed divided large list">


        {% for  real_path, rel_path, dir_names, last_name, tstamp, size, is_image, dir_name, is_dir in paths %}

            <div class="emphasize file {% if plugin and real_path|endswith:'.html' %}plugin{% endif %} item"
                 data-value="{{ dir_name }}/{{ last_name }}" data-plugin="{{ plugin }}">
                <span>

                    {% if uid %}

                        <a href="{% url serve_view uid=uid path=rel_path %}">
                            {% if is_image %}
                                <img class="ui small middle aligned image"
                                     src="{% url serve_view uid=uid path=rel_path %}">
                            {% endif %}
                            {{ rel_path }}
                        </a>
                    {% else %}

                        {% if is_dir %}
                            <a href="{% url 'file_list' rel_path %}"> {{ real_path }}/</a>
                        {% else %}
                            {{ real_path }}
                        {% endif %}

                    {% endif %}

                </span>
                {% if user.is_authenticated %}
                    <a class="ui small right floated label copy"> COPY</a>
                {% endif %}

                <span class="ui right floated small label">{{ size|filesizeformat }}</span>

                {% if plugin and real_path|endswith:'.html' %}
                    <div class="ui right floated small blue label">
                        <i class="expand icon"></i>{{ plugin|upper }}
                    </div>
                {% endif %}

            </div>
        {% endfor %}
    </div>

{% else %}

    <div class="ui icon info message">
        <i class="exclamation triangle icon"></i>
        <div class="content">
            <div class="header">
                No files were found
            </div>
        </div>
    </div>
{% endif %}

biostar/recipes/templates/widgets/form_errors.html
{% if errorlist %}

    <div class="ui red message">
        <div class="ui icons list">
            {% for name, message in errorlist %}
                <div class="item">
                    <i class="warning circle icon"></i>
                    <div class="content">
                        {{ name }} {{ message }}
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endif %}

biostar/recipes/templates/widgets/job_elapsed.html
{% load humanize %}

{% load engine_tags %}
    <div class="ui {% job_color job %} label {{ check_back }}" data-state="{{ job.state }}">

        {% if job.state == job.SPOOLED or job.state == job.RUNNING %}
            <i class="loading circle notch icon"></i>
        {% endif %}
    {{ job.get_state_display }}
    </div>

    {% if job.elapsed %}
        &bull;
        Runtime {{ job.elapsed }}
    {% endif %}

biostar/recipes/templates/widgets/list_view.html
{% load engine_tags %}


{% if projects %}

    <div class="ui vertical large segment">

        <div class="ui divided items">
            {% for project in projects %}
                <div class="item">

                    <img class="ui mytiny circular fancy image" src="{% img project %}"/>

                    <div class="content">

                        <a class="subheader" href="{% url 'recipe_list' project.uid %}">
                            <i class="database icon"></i>{{ project.get_name }}
                        </a>

                        <div class="meta">{{ project.summary|markdown|safe }}
                        </div>
                        <div class="extra">

                            <span class ="ui label">{{ project.get_privacy_display }}</span>

                            <a
                                    href="{% url 'data_list' project.uid %}">
                                <i class="file text icon"></i>{{ project.data_count }} data</a>&bull;

                            <a
                                    href="{% url 'recipe_list' project.uid %}">
                                <i class="setting icon"></i>{{ project.recipes_count }}
                                recipe{{ project.recipes_count|pluralize }}</a>&bull;

                            <a
                                    href="{% url 'job_list' project.uid %}">
                                <i class="bar chart icon"></i>{{ project.jobs_count }}
                                result{{ project.jobs_count|pluralize }}</a>

                            {% created_by date=project.lastedit_date user=project.lastedit_user %}

                        </div>

                    </div>
                </div>


            {% endfor %}
        </div>

    </div>

{% elif data_list %}

    {# Used to list in recycle bin #}

    <div class="ui divided items">
        {% for data in data_list %}

            <div class="item">
                <div class="content">

                    {% if request.user.is_authenticated %}
                        <a class="ui right floated label" href="{% url 'data_delete' data.uid %}">
                            <i class="undo icon"></i> <span class="tablet">Restore</span>
                        </a>
                    {% endif %}

                    <a class="subheader" href="{% url 'data_view' data.uid %}">
                        <i class="file icon"></i>{{ data.get_name }}
                    </a>
                    <div class="meta">
                        <div class="ui small labels">
                            {% size_label data %}
                            {% type_label data %}
                        </div>
                    </div>
                    <div class="meta">{{ data.summary|safe }}</div>
                    <div id="copy-message-{{ data.uid }}"></div>
                </div>
            </div>

        {% endfor %}
    </div>
{% elif recipe_list %}

    {# Used to list in recycle bin #}

    <div class="ui divided link items">
        {% for recipe in recipe_list %}
            <div class="item">
                <div class="">
                    <img class="ui tiny image imgpad" src="{% img recipe %}">
                </div>
                <div class="content">
                    {% if request.user.is_authenticated %}
                        <a class="ui right floated label" href="{% url 'recipe_delete' recipe.uid %}">
                            <i class="undo icon"></i> <span class="tablet">Restore</span>
                        </a>
                    {% endif %}
                    <a class="subheader" href="{% url 'recipe_view' recipe.uid %}">
                        <i class="setting icon"></i> {{ recipe.get_name }}
                    </a>
                    <div class="description">{{ recipe.summary|markdown|safe }}</div>
                    <div id="copy-message-{{ recipe.uid }}"></div>

                </div>
            </div>

        {% endfor %}
    </div>
{% elif job_list %}

    {# Used to list in recycle bin #}

    <div class="ui divided link items">

        {% for job in job_list %}

            <div class="item ">
                <div class="">
                    <img class="ui tiny image imgpad" src="{% img job.analysis %}">
                </div>

                <div class="content">
                    {% if request.user.is_authenticated %}
                        <a class="ui right floated label" href="{% url 'job_delete' job.uid %}">
                            <i class="undo icon"></i> <span class="tablet">Restore</span>
                        </a>
                    {% endif %}

                    <a class="subheader" href="{% url 'job_view' job.uid %}">
                        {% if job.deleted %}Deleted: {% endif %}
                        <i class="bar chart icon"></i>{{ job.name }}
                    </a>

                    <div class="meta">{% job_minutes job %}</div>
                    <div id="copy-message-{{ job.uid }}"></div>
                </div>
            </div>

        {% endfor %}

    </div>
{% endif %}

biostar/recipes/templates/widgets/pages.html
{% load engine_tags %}
{% load humanize %}

<div class="ui page-bar segment">
    {% if objs.has_previous %}
        <a class="ui small basic button no-shadow"
           href="{{ url }}?page={{objs.previous_page_number}}">
            <i class="ui angle  double left icon"> </i>
        </a>
    {% else %}
        <div class="ui small basic button no-shadow">
            <i class="ui angle double left icon"> </i>
        </div>
    {% endif %}

    <span class="phone">{{ objs.paginator.count|intcomma }} result{{ objs.paginator.count|pluralize }} &bull; Page
    </span> {{ objs.number }} of {{ objs.paginator.num_pages }}

    {% if objs.has_next %}

        <a class="ui small basic button no-shadow"
           href="{{ url }}?page={{ objs.next_page_number}}">
            <i class="ui angle  double right icon"></i>
        </a>

    {% else %}

        <div class="ui small basic button no-shadow">
            <i class="ui angle  double right icon"></i>
        </div>

    {% endif %}
</div>

biostar/recipes/templates/widgets/privacy_label.html
{%  if project.is_public %}
    <span class="ui green faded label">{{ project.get_privacy_display }}</span>
{%  else %}
    <span class="ui purple faded label">{{ project.get_privacy_display }}</span>
{%  endif %}

biostar/recipes/templates/widgets/project_title.html
{% load engine_tags %}

<div class="ui center aligned basic vertical segment">
    <div class="ui large header">
        <img class="ui avatar image" src="{% img project %}"/> {{ project.name }}
    </div>

</div>

biostar/recipes/templates/widgets/recipe_clone_message.html
<div class="ui large muted center aligned vertical segment">
    This recipe is a clone. It will remain synchronized with the <a href="{{ recipe.root.url }}">original recipe</a>
</div>

biostar/recipes/templates/widgets/show_messages.html
{% if messages %}
    <div class="padded remove">
        <div class="ui vertical segment">
            {% for message in messages %}
                <div class="ui {{ message.tags }} message">
                    <p>{{ message }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

biostar/recipes/templates/widgets/user_icon.html
{% if user.profile.is_moderator %}
    <i class="ui muted bolt icon"></i>
{%  elif score > 10 %}
    &bull;
{% else %}
    &bull;
{% endif %}
{{ score }}