biostar/forum/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django.urls import include, path  # For django versions from 2.0 and up
import debug_toolbar
from django.views.generic import TemplateView

from biostar.forum import views
from biostar.accounts.views import image_upload_view
from biostar.forum import ajax, api, feed
from biostar.accounts.urls import account_patterns
from biostar.forum.sitemaps import StaticSitemap, DynamicSitemap

from biostar.planet.urls import planet_patterns

sitemaps = {
    'static': StaticSitemap,
    'dynamic': DynamicSitemap
}

forum_patterns = [

    # Main entry. Post listing.
    path('', views.home, name='home'),
    path('latest/', views.latest, name='post_list'),

    path(r'pages/<str:fname>/', views.pages, name='pages'),

    path('votes/', views.myvotes, name='myvotes'),
    path('bookmarks/', views.bookmarks, name='bookmarks'),
    path('following/', views.following, name='following'),
    path('myposts/', views.myposts, name='myposts'),
    path('mytags/', views.mytags, name='mytags'),
    path('p/<str:uid>/', views.post_view, name='post_view'),

    path('post/<slug:slug>/', views.post_slug_details, name='post_view_slug'),

    path('post/search/', views.post_search, name='post_search'),

    path('new/post/', views.new_post, name='post_create'),

    path('b/list/', views.badge_list, name='badge_list'),
    path('t/list/', views.tags_list, name='tags_list'),

    path('b/view/<str:uid>/', views.badge_view, name='badge_view'),

    # Ajax calls
    path('ajax/digest/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/vote/', ajax.ajax_vote, name='vote'),
    path('ajax/test/', ajax.ajax_test, name='ajax_test'),
    path('ajax/subscribe/', ajax.ajax_subs, name='ajax_sub'),
    path('ajax/delete/', ajax.ajax_delete, name='ajax_delete'),
    path('drag/and/drop/', ajax.drag_and_drop, name='drag_and_drop'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/digest/<str:uid>/', ajax.ajax_digest, name='ajax_digest'),
    path('ajax/edit/<str:uid>/', ajax.ajax_edit, name='ajax_edit'),
    path('ajax/comment/create/', ajax.ajax_comment_create, name='ajax_comment_create'),
    path('inplace/form/', ajax.inplace_form, name='inplace_form'),
    path('ajax/user/image/<str:username>/', ajax.user_image, name='user_image'),
    path('similar/posts/<str:uid>/', ajax.similar_posts, name='similar_posts'),
    path('ajax/report/spam/<str:post_uid>/', ajax.report_spam, name='report_spam'),
    path('release/<str:uid>/', ajax.release_suspect, name='release_suspect'),
    #path('most/recent/users/', ajax.most_recent_users, name='most_recent_users'),

    path('moderate/<str:uid>/', views.post_moderate, name="post_moderate"),

    # Community urls
    path('community/', views.community_list, name='community_list'),
    path('ajax/handle/search/', ajax.handle_search, name='handle_search'),

    # Api calls
    path(r'api/traffic/', api.traffic, name='api_traffic'),
    path(r'api/user/<str:uid>/', api.user_details, name='api_user'),
    path(r'api/tags/list/', api.tags_list, name='api_tags_list'),
    path(r'api/post/<str:uid>/', api.post_details, name='api_post'),
    path(r'api/vote/<str:uid>/', api.vote_details, name='api_vote'),
    path(r'api/watched/tags/<str:email>/', api.watched_tags, name='api_tags'),
    path(r'api/email/<str:email>/', api.user_email, name='user_email'),
    path(r'api/stats/day/<int:day>/', api.daily_stats_on_day, name='api_stats_on_day'),
    path(r'api/stats/date/<int:year>/<int:month>/<int:day>/', api.daily_stats_on_date,
         name='api_stats_on_date'),


    # RSS info page.
    path(r'info/rss/', feed.info, name='rss'),

    # RSS feeds
    path(r'feeds/latest/', feed.LatestFeed(), name='latest_feed'),
    path(r'feeds/tag/<str:text>/', feed.TagFeed(), name='tag_feed'),
    path(r'feeds/user/<str:text>/', feed.UserFeed(), name='user_feed'),
    path(r'feeds/post/<str:text>/', feed.PostFeed(), name='post_feed' ),
    path(r'feeds/type/<str:text>/', feed.PostTypeFeed(), name='post_type'),

    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

    #add the robots.txt file
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),



    #path(r'^feeds/planet/$', feed.PlanetFeed(), name='planet-feed'),

]


urlpatterns = [

    # Main entry. Post listing.
    path('', include(forum_patterns)),

    # Include the accounts urls
    path('accounts/', include(account_patterns)),

    # Include the planet urls
    path('planet/', include(planet_patterns)),

]

if settings.PAGEDOWN_IMAGE_UPLOAD_ENABLED:

    urlpatterns += [
        # Pagedown image upload url.
        path('pagedown/image-upload/', image_upload_view, name="pagedown-image-upload")
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

if settings.DEBUG and settings.DEBUG_TOOLBAR:
    urlpatterns += [
          path('__debug__/', include(debug_toolbar.urls)),
    ]

biostar/planet/urls.py
from django.urls import path, include
from biostar.planet import views


planet_patterns = [
    path('', views.blog_list, name="blog_list"),
]
urlpatterns = [

    # Get the reset/ urls
    path(r'', include(planet_patterns)),

]

biostar/server/urls.py
from django.conf import settings
from django.urls import path, include
import debug_toolbar
from django.conf.urls.static import static
from biostar.forum.urls import forum_patterns
from biostar.accounts.views import image_upload_view
from biostar.recipes.urls import recipes_patterns
import biostar.accounts.urls as accounts_urls
from biostar.planet.urls import planet_patterns


urlpatterns = [

    # Mount recipes urls on root.
    path(r'', include(recipes_patterns)),

    # Include forum urls
    path(r'forum/', include(forum_patterns)),

    # Include planets urls
    path(r'planet/', include(planet_patterns)),

    # Include the accounts urls
    path(r'accounts/', include(accounts_urls)),

]

if settings.PAGEDOWN_IMAGE_UPLOAD_ENABLED:

    urlpatterns += [
        # Pagedown image upload url.
        path('pagedown/image-upload/', image_upload_view, name="pagedown-image-upload")
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT, show_indexes=True)

biostar/urls.py
# Default url patters for the engine.
urlpatterns = []



biostar/accounts/models.py
import uuid
import os
from datetime import datetime, timedelta
from taggit.managers import TaggableManager
import mistune
from taggit.models import Tag
from django.conf import settings
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.db import models
from biostar.accounts import util


def fixcase(name):
    return name.upper() if len(name) == 1 else name.lower()


MAX_UID_LEN = 255
MAX_NAME_LEN = 255
MAX_TEXT_LEN = 10000
MAX_FIELD_LEN = 1024


class ProfileManager(models.Manager):

    def valid_users(self):
        """
        Return valid user queryset, filtering new and trusted users.
        """

        # Filter for new or trusted users.
        query = super().get_queryset().filter(models.Q(state=Profile.TRUSTED) | models.Q(state=Profile.NEW))

        return query


def image_path(instance, filename):

    # Assign personal uid our own file name.

    fname = util.get_uuid(32)

    # Name the data by the filename.
    imgpath = os.path.join(settings.PAGEDOWN_IMAGE_UPLOAD_PATH, fname)

    return imgpath


class UserImage(models.Model):

    user = models.ForeignKey(User, null=True, on_delete=models.SET_NULL)

    # Image file path, relative to MEDIA_ROOT
    image = models.ImageField(default=None, blank=True, upload_to=image_path, max_length=MAX_FIELD_LEN)


class Profile(models.Model):
    NEW, TRUSTED, SUSPENDED, BANNED, SPAMMER = range(5)
    STATE_CHOICES = [(NEW, "New"), (TRUSTED, "Active"), (SPAMMER, "Spammer"),
                     (SUSPENDED, "Suspended"), (BANNED, "Banned")]
    state = models.IntegerField(default=NEW, choices=STATE_CHOICES, db_index=True)

    READER, MODERATOR, MANAGER, BLOGGER = range(4)
    ROLE_CHOICES = [
        (READER, "Reader"), (MODERATOR, "Moderator"), (MANAGER, "Admin"),
        (BLOGGER, "Blog User")
    ]

    NO_DIGEST, DAILY_DIGEST, WEEKLY_DIGEST, MONTHLY_DIGEST, ALL_MESSAGES = range(5)

    DIGEST_CHOICES = [(NO_DIGEST, 'Never'), (DAILY_DIGEST, 'Daily'),
                      (WEEKLY_DIGEST, 'Weekly'), (MONTHLY_DIGEST, 'Monthly'),
                      (ALL_MESSAGES, "Email for every new thread (mailing list mode)")
                      ]
    # Subscription to daily and weekly digests.
    digest_prefs = models.IntegerField(choices=DIGEST_CHOICES, default=NO_DIGEST)

    LOCAL_MESSAGE, EMAIL_MESSAGE, NO_MESSAGES, DEFAULT_MESSAGES = range(4)
    MESSAGING_TYPE_CHOICES = [
        (DEFAULT_MESSAGES, "Default"),
        (EMAIL_MESSAGE, "Email"),
        (LOCAL_MESSAGE, "Local Messages"),
        (NO_MESSAGES, "No messages"),

    ]
    # Default subscriptions inherit from this
    message_prefs = models.IntegerField(choices=MESSAGING_TYPE_CHOICES, default=DEFAULT_MESSAGES)

    # Connection to the user.
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    # User unique id (handle)
    uid = models.CharField(max_length=MAX_UID_LEN, unique=True)

    # User diplay name.
    name = models.CharField(max_length=MAX_NAME_LEN, default='', db_index=True)

    # Maximum amount of uploaded files a user is allowed to aggregate, in mega-bytes.
    max_upload_size = models.IntegerField(default=0)

    # The role of the user.
    role = models.IntegerField(default=READER, choices=ROLE_CHOICES)

    # User token used to
    token = models.CharField(default="", max_length=255, blank=True)

    # The date the user last logged in.
    last_login = models.DateTimeField(null=True, max_length=255, db_index=True)

    # The number of new messages for the user.
    new_messages = models.IntegerField(default=0, db_index=True)

    # The last visit by the user.
    date_joined = models.DateTimeField(max_length=255)

    # User provided location.
    location = models.CharField(default="", max_length=255, blank=True, db_index=True)

    # User provided website.
    website = models.URLField(default="", max_length=256, blank=True)

    # Google scholar ID
    scholar = models.CharField(default="", max_length=255, blank=True)

    # User reputation score.
    score = models.IntegerField(default=0, db_index=True)

    # Twitter ID
    twitter = models.CharField(default="", max_length=255, blank=True)

    # This field is used to select content for the user.
    my_tags = models.CharField(default="", max_length=MAX_TEXT_LEN, blank=True)

    # The tag value is the canonical form of the post's tags
    watched_tags = models.TextField(max_length=MAX_TEXT_LEN, default="", blank=True)

    # Tag objects
    watched = TaggableManager()

    # Description provided by the user html.
    text = models.TextField(default="No profile information", null=True, max_length=MAX_TEXT_LEN, blank=True)

    # The html version of the user information.
    html = models.TextField(null=True, max_length=MAX_TEXT_LEN, blank=True)

    # The state of the user email verification.
    email_verified = models.BooleanField(default=False)

    # Automatic notification
    notify = models.BooleanField(default=False)

    # Opt-in to all messages from the site
    opt_in = models.BooleanField(default=False)

    objects = ProfileManager()

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.uid = self.uid or util.get_uuid(8)
        self.html = self.html or mistune.markdown(self.text)
        self.max_upload_size = self.max_upload_size or self.set_upload_size()
        self.name = self.name or self.user.first_name or self.user.email.split("@")[0]
        self.date_joined = self.date_joined or util.now()
        self.last_login = self.last_login or util.now() #- timedelta(days=1)
        self.token = self.token or util.get_uuid(16)

        super(Profile, self).save(*args, **kwargs)

    @property
    def state_dict(self):
        return dict(self.STATE_CHOICES)

    @property
    def upload_size(self):

        # Give staff higher limits.
        if self.user.is_staff or self.user.is_superuser:
            return self.max_upload_size * 100
        return self.max_upload_size

    def parse_tags(self):
        return [tag.lower() for tag in self.watched_tags.split(",") if tag]

    def add_watched(self):
        tags = [Tag.objects.get_or_create(name=name)[0] for name in self.parse_tags()]
        self.watched.remove()
        self.watched.add(*tags)

    def set_upload_size(self):
        """
        Used to set the inital value
        """

        # Admin users upload limit
        if self.user.is_superuser or self.user.is_staff:
            return settings.ADMIN_UPLOAD_SIZE
        # Trusted users upload limit
        if self.user.profile.trusted:
            return settings.TRUSTED_UPLOAD_SIZE

        # Get the default upload limit
        return settings.MAX_UPLOAD_SIZE

    def require_recaptcha(self):
        """Check to see if this user requires reCAPTCHA"""
        is_required = not (self.trusted or self.score > settings.RECAPTCHA_THRESHOLD_USER_SCORE)
        return is_required

    @property
    def mailing_list(self):
        """
        User has mailing list mode turned on.
        """
        return self.digest_prefs == self.ALL_MESSAGES

    def get_score(self):
        """
        """
        score = self.score * 10
        return score

    @property
    def is_moderator(self):
        # Managers can moderate as well.
        return self.role == self.MODERATOR or self.role == self.MANAGER or self.user.is_staff or self.user.is_superuser

    @property
    def trusted(self):
        return (self.user.is_staff or self.state == self.TRUSTED or
                self.role == self.MODERATOR or self.role == self.MANAGER or self.user.is_superuser)

    @property
    def is_manager(self):
        return self.role == self.MANAGER

    def get_absolute_url(self):

        return reverse('user_profile', kwargs=dict(uid=self.uid))

    @property
    def is_suspended(self):
        return self.state == self.SUSPENDED

    @property
    def is_banned(self):
        return self.state == self.BANNED

    @property
    def is_spammer(self):
        return self.state == self.SPAMMER

    @property
    def is_valid(self):
        """
        User is not banned, suspended, or banned
        """
        return not self.is_spammer and not self.is_suspended and not self.is_banned

    @property
    def recently_joined(self):
        """
        User that joined X amount of days are considered new.
        """
        recent = (util.now() - self.date_joined).days > settings.RECENTLY_JOINED_DAYS
        return recent

    def bump_over_threshold(self):

        # Bump the score by smallest values to get over the low rep threshold.
        score = self.score
        score += 1 + (settings.LOW_REP_THRESHOLD - self.score)

        Profile.objects.filter(id=self.id).update(score=score)

    @property
    def low_rep(self):
        """
        User has a low score
        """
        return self.score <= settings.LOW_REP_THRESHOLD and not self.is_moderator


class Logger(models.Model):
    # Put in delte
    MODERATING, CREATION, EDIT, LOGIN, LOGOUT, BROWSING = range(6)

    ACTIONS_CHOICES = [(MODERATING, "Preformed a moderation action."),
                       (CREATION, "Created an object."),
                       (EDIT, "Edited an object."),
                       (LOGIN, "Logged in to the site."),
                       (LOGOUT, "Logged out of the site."),
                       (BROWSING, "Browsing the site.")]

    # User that preformed this action
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    # Action this user is took.
    action = models.IntegerField(choices=ACTIONS_CHOICES, default=BROWSING)

    # Stores the specific log text
    log_text = models.TextField(default='')

    # Date this log was created
    date = models.DateTimeField(auto_now_add=True)


# Connects user to message bodies
class MessageBody(models.Model):
    """
    A message that may be shared across all users.
    """
    body = models.TextField(max_length=MAX_TEXT_LEN)

biostar/forum/templates/accounts/edit_profile.html
{% extends "forum_base.html" %}
{% load forum_tags %}
{% load accounts_tags %}

{% block headtitle %}Edit Profile{% endblock %}

{% block content %}

    <div class="ui horizontal segments no-shadow">

        <div class="ui segment  no-shadow"></div>
        <div class="ui basic compact segment no-shadow">

            <form method="post" class="ui equal width form" action="{% url 'edit_profile' %}">
                {{ form.media }}
                {% csrf_token %}

                {% form_errors form %}

                <div class="ui basic center aligned segment">
                    <span class="ui header">Update Profile</span>
                </div>

                <div class="fields">
                    <div class="empty form-field field"></div>

                    <div class="required form-field field">
                        <div class="ui form-wrap segment">
                            <label><i class="address card icon"></i>Name </label>
                            {{ form.name }}
                            <div class="muted">
                                Displayed name
                            </div>
                        </div>
                    </div>

                    <div class="empty form-field field"></div>
                </div>

                <div class="fields">
                    <div class="empty form-field field"></div>

                    <div class="required form-field field">
                        <div class="ui form-wrap segment">
                            <label><i class="at icon"></i>Handle</label>
                            {{ form.username }}
                            <div class="muted">
                                Handle may be used to reference you in posts.
                            </div>
                        </div>
                    </div>

                    <div class="empty form-field field"></div>
                </div>
                <div class="fields">
                    <div class="empty form-field field"></div>

                    <div class="required form-field field">
                        <div class="ui form-wrap segment">
                            <label><i class="envelope icon"></i>Email</label>
                            {{ form.email }}
                            <div class="muted">
                                Email used to register to the site.
                            </div>
                        </div>
                    </div>

                    <div class="empty form-field field"></div>
                </div>

                <div class="fields">

                    <div class="field">
                        <div class="ui form-wrap segment">
                            <label><i class="linkify icon"></i>Website</label>
                            {{ form.website }}
                            <div class="muted">
                                URL to your website
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui form-wrap segment">
                            <label><i class="map marker alternate icon"></i>Location</label>
                            {{ form.location }}
                            <div class="muted">
                                Country/City/Institution
                            </div>
                        </div>
                    </div>


                </div>


                <div class="fields">
                    <div class="field">
                        <div class="ui form-wrap segment">

                            <label><i class="twitter icon"></i>Twitter id</label>
                            {{ form.twitter }}
                            <div class="muted">
                                Your twitter id
                            </div>
                        </div>
                    </div>

                    <div class="field">
                        <div class="ui form-wrap segment">
                            <label><i class="google icon"></i>Scholar</label>
                            {{ form.scholar }}
                            <div class="muted">
                                Your Google Scholar ID
                            </div>
                        </div>
                    </div>
                </div>
                <div class="fields">

                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="bell icon"></i>Digest Preferences </label>
                            {{ form.digest_prefs }}
                            <div class="muted">
                                {{ form.digest_prefs.help_text }}
                            </div>
                        </div>
                    </div>

                </div>
                <div class="fields">

                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="bell icon"></i>Notifications </label>
                            {{ form.message_prefs }}
                            <div class="muted">
                                {{ form.message_prefs.help_text }}
                            </div>
                        </div>
                    </div>

                </div>

                <div class="fields">
                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="tags icon"></i>My Tags </label>

                            {% tags_field form_field=form.my_tags initial=user.profile.my_tags %}

                            <div class="muted">
                                Post with tags listed here will show up in the My Tags tab.
                                Example: <code>galaxy</code>, <code>bed</code>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="fields">
                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="tags icon"></i>Watched Tags </label>

                            {% tags_field form_field=form.watched_tags initial=user.profile.watched_tags %}

                            <div class="muted">
                                Get email when a post matching the tag is posted. Limit of 500.
                                Example: <code>minia</code>, <code>bedops</code>, <code>breakdancer</code>,
                                <code>music</code>.
                            </div>
                        </div>
                    </div>
                </div>

                <div class="fields">

                    <div class="field">
                        <div class="ui form-wrap segment" style="display: grid">
                            <label><i class="info icon"></i>Description</label>
                            {{ form.text }}
                            <div class="muted">
                                {{ form.text.help_text }}
                            </div>
                        </div>
                    </div>

                </div>

                <button type="submit" class="ui submit green button">
                    <i class="save icon"></i>Submit
                </button>

                <a class="ui right floated button" href="{% url "user_profile" user.profile.uid %}">
                    <i class="undo icon"></i>Cancel
                </a>


            </form>
        </div>

        <div class="ui segment no-shadow"></div>
    </div>


{% endblock %}

biostar/forum/templates/accounts/logout.html
{% extends "forum_base.html" %}
{% load forum_tags %}
{% load accounts_tags %}

{% block headtitle %} Biostar Forum {% endblock %}
{% block title %} Log out {% endblock %}

{% block content %}

     <form method="post" action="{% url 'logout' %}" >

        <div class="ui center aligned header">

            <i class="sign out icon"></i>Do you want to log out?

        </div>
        <div class="ui centered card inputcolor">

            <div class="ui basic segment">
                    {% csrf_token %}
                    <button class="ui primary button" type="submit"> <i class="sign out icon"></i> Log out</button>
                    <a class="ui right floated  button" href="/"> <i class="home icon"></i>Home</a>
            </div>
        </div>
 </form>
{% endblock %}

biostar/forum/templates/accounts/user_profile.html
{% extends "forum_base.html" %}
{% load accounts_tags %}
{% load forum_tags %}
{% block headtitle %}{{ target.profile.name }}{% endblock %}

{% block content %}

    <div class="ui stackable three column grid profile" data-value="{{ target.profile.id }}">

        <div class="column">
            <div class="ui center aligned  basic segment">
                <img class="ui centered circular image" src="{% gravatar user=target size=150 %}">
                <div class="ui centered header">
                    {{ target.profile.name }}
                    {% user_icon score=target.profile.score %}
                </div>
            </div>

            <div class="ui center aligned basic segment">

                {% if target == request.user %}
                    <a class="ui mini button" href="{% url 'edit_profile' %}">
                        <i class="write icon"></i>Edit profile
                    </a>
                {% endif %}

                {% if can_moderate %}
                    <div class="ui mini button orange moderate">
                        <i class="hand paper icon"></i>
                        Moderate
                    </div>
                {% endif %}

                {% if request.user.is_superuser and debugging %}
                    <a class="ui mini red button" href="{% url 'debug_user' %}?uid={{ target.profile.uid }}">
                        <i class="sign in icon"></i> Log in
                    </a>
                {% endif %}

            </div>

            <div id="mod"></div>
        </div>

        <div class="column">


            <div class="ui center aligned basic segment">


                <table class="ui very basic table profile">
                    <tbody>

                    {% if target.profile.is_moderator %}
                        <tr>
                            <td>Role:</td>
                            <td>{{ target.profile.get_role_display }}</td>
                        </tr>
                    {% endif %}

                    <tr>
                        <td>Status:</td>
                        <td>{{ target.profile.get_state_display }}</td>
                    </tr>

                    <tr>
                        <td>Handle:</td>
                        <td><code>@{{ target.username }}</code></td>
                    </tr>

                    <tr>
                        <td>Reputation:</td>
                        <td>{{ target.profile.get_score }}</td>
                    </tr>
                    {% if target == request.user or request.user.profile.is_moderator %}
                        <tr>
                            <td>Email:</td>
                            <td>{{ target.email }}</td>
                        </tr>
                    {% endif %}

                    <tr>
                        <td>Joined:</td>
                        <td>{{ target.profile.date_joined|time_ago }}</td>
                    </tr>

                    {% if target.profile.twitter %}
                        <tr>
                            <td>Twitter:</td>
                            <td>
                                <a href="https://twitter.com/{{ target.profile.twitter }}"><i
                                        class="twitter icon"></i>{{ target.profile.twitter }}</a>
                            </td>
                        </tr>
                    {% endif %}

                    {% if target.profile.scholar %}
                        <tr>
                            <td>Google Scholar:</td>
                            <td>
                                <a href="https://scholar.google.com/citations?user={{ target.profile.scholar }}"><i
                                        class="book icon"></i>{{ target.profile.scholar }}</a>
                            </td>
                        </tr>
                    {% endif %}
                    {% if target == request.user %}
                        <tr>
                            <td>Notifications:</td>
                            <td>{{ target.profile.get_message_prefs_display }}</td>
                        </tr>
                    {% endif %}

                    <tr>
                        <td>Last seen:</td>
                        <td>{{ target.profile.last_login |time_ago }}</td>
                    </tr>
                    {% if show_info %}
                        <tr>
                            <td>Location:</td>
                            <td>{{ target.profile.location }}</td>
                        </tr>
                    {% endif %}
                    </tbody>
                </table>

            </div>


        </div>
        <div class="column">
            <div class="profile ui relaxed divided list profile">

                <div class="item">
                    <div class="content">

                        {% if show_info %}
                            <p>{{ target.profile.html |safe }}</p>
                        {% else %}
                            <p>
                                Profile information, website and location are not shown for new users.
                            </p>
                            <p>
                                This helps us discourage the inappropriate use of our site.
                            </p>

                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="ui vertical segment">

        <div class="ui top attached tabular  menu">

            <a class="{% activate 'posts' active %} item" href="{{ target.profile.get_absolute_url }}?active=posts">
                <i class="list alternate outline icon"></i><span class="phone"> Posts</span>
            </a>

            <a class="{% activate 'awards' active %}  item" href="{{ target.profile.get_absolute_url }}?active=awards">
                <i class="star outline icon"></i><span class="phone">Awards</span>
            </a>

        </div>
        <div class="ui bottom attached profile segment">
            {% if active == 'posts' %}

                {% include 'accounts/profile_post_listing.html' %}

            {% else %}
                {% list_awards target=target %}
            {% endif %}
        </div>
    </div>

{% endblock %}